# Generated by Django 3.1.4 on 2021-02-04 07:16

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='context',
            field=models.TextField(default=django.utils.timezone.now, verbose_name='Contenido'),
        ),
    ]
