# Generated by Django 3.1.4 on 2021-02-13 06:19

import ckeditor.fields
from django.db import migrations
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_auto_20210206_1821'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='context',
            field=ckeditor.fields.RichTextField(default=django.utils.timezone.now, verbose_name='Contenido'),
        ),
    ]
