# Generated by Django 3.1.4 on 2021-02-06 21:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('social', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='social',
            new_name='Link',
        ),
    ]
