# Generated by Django 3.1.4 on 2021-02-04 03:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0002_auto_20210203_1926'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Services_app',
            new_name='Service',
        ),
    ]
