# Generated by Django 3.1.4 on 2021-02-04 04:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0003_auto_20210204_0009'),
    ]

    operations = [
        migrations.RenameField(
            model_name='service',
            old_name='subtitlle',
            new_name='subtitle',
        ),
    ]
