# Generated by Django 3.1.4 on 2021-02-13 06:19

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0004_auto_20210204_0139'),
    ]

    operations = [
        migrations.AlterField(
            model_name='service',
            name='context',
            field=ckeditor.fields.RichTextField(verbose_name='Contexto'),
        ),
    ]
